/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    categories: Category;
    families: Family;
    products: Product;
    variants: Variant;
    specifications: Specification;
    media: Media;
    'reusable-blocks': ReusableBlock;
    blogs: Blog;
    audits: Audit;
    roles: Role;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      families: 'families';
    };
    products: {
      auditDays: 'audits';
    };
    variants: {
      specs: 'specifications';
    };
  };
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    families: FamiliesSelect<false> | FamiliesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    specifications: SpecificationsSelect<false> | SpecificationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'reusable-blocks': ReusableBlocksSelect<false> | ReusableBlocksSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    audits: AuditsSelect<false> | AuditsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  badge?: string | null;
  slug?: string | null;
  sortOrder?: number | null;
  description?: string | null;
  shortDescription?: string | null;
  /**
   * Legacy coarser badge (preserved, not canonical)
   */
  badgeAlias?: string | null;
  catalogPdf?: (number | null) | Media;
  /**
   * products.json catalogPdf string path
   */
  catalogPdfUrl?: string | null;
  /**
   * products.json category name (verbatim)
   */
  jsonName?: string | null;
  /**
   * products.json category badge (verbatim)
   */
  jsonBadge?: string | null;
  /**
   * products.json category catalogPdf (verbatim)
   */
  jsonPdf?: string | null;
  families?: {
    docs?: (number | Family)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The image library. Drag an image here (or click + Upload New) and give it a clear name. You can then attach it to a product or blog from that product/blog editor. Images with no "Name / alt text" show a date-based placeholder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short, clear name — it appears in every picker, and is also used as the image alt text on the website (e.g. "GM412115 cross section").
   */
  alt?: string | null;
  /**
   * What this image is typically used for (informational).
   */
  kind?: ('image' | 'technicalDrawing' | 'drawing' | 'gallery' | '3d' | 'main' | 'cover' | 'logo' | 'other') | null;
  /**
   * Optional note for cropping (e.g. "focus left side"). Rarely needed.
   */
  croppedTo?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families".
 */
export interface Family {
  id: number;
  code: string;
  name?: string | null;
  /**
   * Family type (schema-v2). Drives variant attribute blocks.
   */
  type: 'PROFILE' | 'ANCHOR' | 'FASTENER' | 'CLAMP' | 'ACCESSORY';
  productName: string;
  productNameAlias?: string | null;
  category: string;
  categoryAlias?: string | null;
  shortDescription?: string | null;
  definition?: string | null;
  fullName?: string | null;
  series?: string | null;
  badge?: string | null;
  sortOrder?: number | null;
  brand?: string | null;
  productRange?: string | null;
  website?: string | null;
  categoryID?: (number | null) | Category;
  /**
   * Source contract file
   */
  file?: string | null;
  /**
   * Original export key casing (e.g. greengrip ggtcTriLock)
   */
  contractKey?: string | null;
  /**
   * Badge verbatim from the source contract file (may differ from category doc)
   */
  fileBadge?: string | null;
  /**
   * Category description verbatim from the source contract file
   */
  fileDescription?: string | null;
  /**
   * Parse order within source file
   */
  order?: number | null;
  /**
   * Accessory code_prefix verbatim
   */
  codePrefix?: string | null;
  /**
   * Unmodeled top-level source keys (e.g. components)
   */
  extra?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  catalogPdf?: (number | null) | Media;
  pdfPage?: string | null;
  mountingMethod?: string | null;
  technicalData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  specifications?:
    | {
        key: string;
        value?: string | null;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Photos & drawings for this family. Pick an uploaded library image per row, or keep an existing path.
   */
  images?:
    | {
        /**
         * Main photo, technical drawing, gallery...
         */
        kind?:
          ('image' | 'technicalDrawing' | 'drawing' | 'gallery' | '3d' | 'main' | 'cover' | 'logo' | 'other') | null;
        /**
         * Choose one of your uploaded images. Preferred — published automatically (assets/img/).
         */
        media?: (number | null) | Media;
        /**
         * Existing path or URL. Only when the library picker above is empty.
         */
        path?: string | null;
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  tables?:
    | {
        id?: string | null;
        label?: string | null;
        columns?:
          | {
              column?: string | null;
              id?: string | null;
            }[]
          | null;
        rows?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product catalogue. Click a product to open it, edit any field, then press "Save". Changes are applied to the website the next time content is published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Unique product code. Used to look products up and in catalog exports.
   */
  sku: string;
  /**
   * The family this product belongs to (e.g. Strut Channel, Metal Anchor). Pick from the list.
   */
  family?: (number | null) | Family;
  /**
   * Short tagline shown under the product name (catalog exports).
   */
  subtitle?: string | null;
  /**
   * Contract file this product was imported from. Managed automatically — not editable.
   */
  file?: string | null;
  /**
   * Internal grouping key used to place this product in the website catalog. Managed by import.
   */
  categoryId?: string | null;
  /**
   * Position of this product within its catalog group. Managed by import.
   */
  order?: number | null;
  /**
   * Page number in the original price list/PDF. For reference only.
   */
  page?: number | null;
  /**
   * Optional reusable specification/load table attached to this product.
   */
  specSet?: (number | null) | ReusableBlock;
  auditDays?: {
    docs?: (number | Audit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Full product name — shown as the product title on the website.
   */
  productName?: string | null;
  /**
   * Alternative name used in some catalog listings.
   */
  productNameAlias?: string | null;
  /**
   * Main category this product is displayed under.
   */
  category?: string | null;
  /**
   * Alternative category label used in some listings.
   */
  categoryAlias?: string | null;
  /**
   * Brand name (e.g. GRIP).
   */
  brand?: string | null;
  /**
   * Range name this product belongs to, if any.
   */
  productRange?: string | null;
  /**
   * Short summary shown on catalog cards and list pages. (Supports normal text.)
   */
  shortDescription?: string | null;
  /**
   * Longer legacy description text where available.
   */
  description?: string | null;
  /**
   * Longer definition of the category this product belongs to.
   */
  categoryDefinition?: string | null;
  /**
   * Fact sheet shown on the product page. Add a row for each specification.
   */
  specifications?:
    | {
        key: string;
        value?: string | null;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Reserved for a library-linked main image. Most products use the rows below instead.
   */
  image?: (number | null) | Media;
  /**
   * Add one row per image. The first row of each "Use" is what the website shows.
   */
  images?:
    | {
        /**
         * Main photo, technical drawing, gallery...
         */
        kind?:
          ('image' | 'technicalDrawing' | 'drawing' | 'gallery' | '3d' | 'main' | 'cover' | 'logo' | 'other') | null;
        /**
         * Choose one of your uploaded images. Preferred — the page will publish it automatically (stored under assets/img/).
         */
        media?: (number | null) | Media;
        /**
         * Existing path or URL (e.g. assets/... ). Only fill this in when the library picker above is left empty.
         */
        path?: string | null;
        /**
         * Optional identifier (e.g. GM412115).
         */
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        sku: string;
        size?: string | null;
        loadRating?: string | null;
        loadCases?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        dimensions?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        attributes?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How this product is mounted/installed.
   */
  mountingMethod?: string | null;
  technicalData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  technicalTable?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  properties?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  loadCases?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-blocks".
 */
export interface ReusableBlock {
  id: number;
  name: string;
  /**
   * Reusable block kind (plan §3 #9).
   */
  type?: ('table' | 'spec-group' | 'definition' | 'demo') | null;
  block?:
    | (
        | {
            title?: string | null;
            rows?:
              | {
                  key?: string | null;
                  value?: string | null;
                  unit?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'specTable';
          }
        | {
            caseName?: string | null;
            span?: string | null;
            load?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'loadTable';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audits".
 */
export interface Audit {
  id: number;
  operation: string;
  leaf?: string | null;
  decisionId?: string | null;
  contract?: string | null;
  beforeValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  afterValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  resolution?: (number | null) | Family;
  product?: (number | null) | Product;
  at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  sku: string;
  /**
   * Source contract file
   */
  file?: string | null;
  code?: string | null;
  product: number | Product;
  family?: (number | null) | Family;
  size?: string | null;
  packSize?: string | null;
  unit?: string | null;
  weight?: number | null;
  loadRating?: string | null;
  image?: (number | null) | Media;
  notes?: string | null;
  attributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  specs?: {
    docs?: (number | Specification)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specifications".
 */
export interface Specification {
  id: number;
  family: number | Family;
  variant?: (number | null) | Variant;
  key: string;
  value?: string | null;
  unit?: string | null;
  order?: number | null;
  fullCopy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog & news articles. Write the article in the visual editor, set a publish date, then set Status to "Published" so it appears on the website after publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  /**
   * The headline shown on the blog card and article page.
   */
  title: string;
  /**
   * Short teaser text shown on the blog card. Leave blank to hide it.
   */
  excerpt?: string | null;
  /**
   * Write the article here using the visual editor (bold, headings, lists, links, tables). No HTML needed.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Draft articles are hidden from the website until you switch this to "Published".
   */
  status?: ('published' | 'draft') | null;
  /**
   * Web address ending for this article (e.g. my-article). Leave blank to auto-create from the title.
   */
  slug: string;
  /**
   * Filter label used on the blog page (e.g. Product Guides, Installation, Technical).
   */
  category?: string | null;
  /**
   * Team member this article is credited to.
   */
  author?: (number | null) | User;
  /**
   * Date shown on the article. Newest dates appear first in the blog list.
   */
  publishedAt?: string | null;
  /**
   * e.g. "5 min read".
   */
  readTime?: string | null;
  /**
   * Used automatically when no library image is chosen below. Existing articles keep their path/URL here — leave as-is.
   */
  image?: string | null;
  /**
   * Pick one of your uploaded images for this article. When set, it is used instead of the legacy path above. Upload new images in the Images collection.
   */
  coverImage?: (number | null) | Media;
  /**
   * Highlight this article on the blog page.
   */
  featured?: boolean | null;
  /**
   * Optional labels/topics for this article.
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Used only when the visual "Article body" editor above is empty. Existing legacy articles keep their HTML here — you can leave it as-is.
   */
  contentHtml?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  isAdmin?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  isAdmin?: boolean | null;
  isOwner?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'families';
        value: number | Family;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'specifications';
        value: number | Specification;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'reusable-blocks';
        value: number | ReusableBlock;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'audits';
        value: number | Audit;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  badge?: T;
  slug?: T;
  sortOrder?: T;
  description?: T;
  shortDescription?: T;
  badgeAlias?: T;
  catalogPdf?: T;
  catalogPdfUrl?: T;
  jsonName?: T;
  jsonBadge?: T;
  jsonPdf?: T;
  families?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families_select".
 */
export interface FamiliesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  type?: T;
  productName?: T;
  productNameAlias?: T;
  category?: T;
  categoryAlias?: T;
  shortDescription?: T;
  definition?: T;
  fullName?: T;
  series?: T;
  badge?: T;
  sortOrder?: T;
  brand?: T;
  productRange?: T;
  website?: T;
  categoryID?: T;
  file?: T;
  contractKey?: T;
  fileBadge?: T;
  fileDescription?: T;
  order?: T;
  codePrefix?: T;
  extra?: T;
  catalogPdf?: T;
  pdfPage?: T;
  mountingMethod?: T;
  technicalData?: T;
  specifications?:
    | T
    | {
        key?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  images?:
    | T
    | {
        kind?: T;
        media?: T;
        path?: T;
        code?: T;
        id?: T;
      };
  tables?:
    | T
    | {
        id?: T;
        label?: T;
        columns?:
          | T
          | {
              column?: T;
              id?: T;
            };
        rows?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  sku?: T;
  family?: T;
  subtitle?: T;
  file?: T;
  categoryId?: T;
  order?: T;
  page?: T;
  specSet?: T;
  auditDays?: T;
  productName?: T;
  productNameAlias?: T;
  category?: T;
  categoryAlias?: T;
  brand?: T;
  productRange?: T;
  shortDescription?: T;
  description?: T;
  categoryDefinition?: T;
  specifications?:
    | T
    | {
        key?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  image?: T;
  images?:
    | T
    | {
        kind?: T;
        media?: T;
        path?: T;
        code?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        sku?: T;
        size?: T;
        loadRating?: T;
        loadCases?: T;
        dimensions?: T;
        attributes?: T;
        id?: T;
      };
  mountingMethod?: T;
  technicalData?: T;
  technicalTable?: T;
  properties?: T;
  loadCases?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  sku?: T;
  file?: T;
  code?: T;
  product?: T;
  family?: T;
  size?: T;
  packSize?: T;
  unit?: T;
  weight?: T;
  loadRating?: T;
  image?: T;
  notes?: T;
  attributes?: T;
  order?: T;
  specs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specifications_select".
 */
export interface SpecificationsSelect<T extends boolean = true> {
  family?: T;
  variant?: T;
  key?: T;
  value?: T;
  unit?: T;
  order?: T;
  fullCopy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  kind?: T;
  croppedTo?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-blocks_select".
 */
export interface ReusableBlocksSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  block?:
    | T
    | {
        specTable?:
          | T
          | {
              title?: T;
              rows?:
                | T
                | {
                    key?: T;
                    value?: T;
                    unit?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        loadTable?:
          | T
          | {
              caseName?: T;
              span?: T;
              load?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  body?: T;
  status?: T;
  slug?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  image?: T;
  coverImage?: T;
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  contentHtml?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audits_select".
 */
export interface AuditsSelect<T extends boolean = true> {
  operation?: T;
  leaf?: T;
  decisionId?: T;
  contract?: T;
  beforeValue?: T;
  afterValue?: T;
  resolution?: T;
  product?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  isAdmin?: T;
  isOwner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  isAdmin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}