/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const categories = sqliteTable(
  "categories",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    badge: text("badge"),
    slug: text("slug"),
    sortOrder: numeric("sort_order", { mode: "number" }),
    description: text("description"),
    shortDescription: text("short_description"),
    badgeAlias: text("badge_alias"),
    catalogPdf: integer("catalog_pdf_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("categories_catalog_pdf_idx").on(columns.catalogPdf),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const families_specifications = sqliteTable(
  "families_specifications",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    key: text("key").notNull(),
    value: text("value"),
    unit: text("unit"),
  },
  (columns) => [
    index("families_specifications_order_idx").on(columns._order),
    index("families_specifications_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [families.id],
      name: "families_specifications_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const families_images = sqliteTable(
  "families_images",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    kind: text("kind"),
    path: text("path"),
    code: text("code"),
  },
  (columns) => [
    index("families_images_order_idx").on(columns._order),
    index("families_images_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [families.id],
      name: "families_images_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const families_tables_columns = sqliteTable(
  "families_tables_columns",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    column: text("column"),
  },
  (columns) => [
    index("families_tables_columns_order_idx").on(columns._order),
    index("families_tables_columns_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [families_tables.id],
      name: "families_tables_columns_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const families_tables = sqliteTable(
  "families_tables",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label"),
    rows: text("rows", { mode: "json" }),
  },
  (columns) => [
    index("families_tables_order_idx").on(columns._order),
    index("families_tables_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [families.id],
      name: "families_tables_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const families = sqliteTable(
  "families",
  {
    id: integer("id").primaryKey(),
    code: text("code").notNull(),
    name: text("name"),
    type: text("type", {
      enum: ["PROFILE", "ANCHOR", "FASTENER", "CLAMP", "ACCESSORY"],
    }).notNull(),
    productName: text("product_name").notNull(),
    productNameAlias: text("product_name_alias"),
    category: text("category").notNull(),
    categoryAlias: text("category_alias"),
    shortDescription: text("short_description"),
    definition: text("definition"),
    fullName: text("full_name"),
    series: text("series"),
    badge: text("badge"),
    sortOrder: numeric("sort_order", { mode: "number" }),
    brand: text("brand"),
    productRange: text("product_range"),
    website: text("website"),
    categoryID: integer("category_i_d_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    catalogPdf: integer("catalog_pdf_id").references(() => media.id, {
      onDelete: "set null",
    }),
    pdfPage: text("pdf_page"),
    mountingMethod: text("mounting_method"),
    technicalData: text("technical_data", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("families_code_idx").on(columns.code),
    index("families_type_idx").on(columns.type),
    index("families_category_i_d_idx").on(columns.categoryID),
    index("families_catalog_pdf_idx").on(columns.catalogPdf),
    index("families_updated_at_idx").on(columns.updatedAt),
    index("families_created_at_idx").on(columns.createdAt),
  ],
);

export const products_images = sqliteTable(
  "products_images",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    kind: text("kind"),
    path: text("path"),
    code: text("code"),
  },
  (columns) => [
    index("products_images_order_idx").on(columns._order),
    index("products_images_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_images_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_specifications = sqliteTable(
  "products_specifications",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    key: text("key").notNull(),
    value: text("value"),
    unit: text("unit"),
  },
  (columns) => [
    index("products_specifications_order_idx").on(columns._order),
    index("products_specifications_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_specifications_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products_variants = sqliteTable(
  "products_variants",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    sku: text("sku").notNull(),
    size: text("size"),
    loadRating: text("load_rating"),
    loadCases: text("load_cases", { mode: "json" }),
    dimensions: text("dimensions", { mode: "json" }),
    attributes: text("attributes", { mode: "json" }),
  },
  (columns) => [
    index("products_variants_order_idx").on(columns._order),
    index("products_variants_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_variants_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products = sqliteTable(
  "products",
  {
    id: integer("id").primaryKey(),
    sku: text("sku").notNull(),
    productName: text("product_name"),
    productNameAlias: text("product_name_alias"),
    category: text("category"),
    categoryAlias: text("category_alias"),
    family: integer("family_id")
      .notNull()
      .references(() => families.id, {
        onDelete: "set null",
      }),
    brand: text("brand"),
    productRange: text("product_range"),
    pageNumber: numeric("page_number", { mode: "number" }),
    description: text("description"),
    shortDescription: text("short_description"),
    categoryDefinition: text("category_definition"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    mountingMethod: text("mounting_method"),
    technicalData: text("technical_data", { mode: "json" }),
    technicalTable: text("technical_table", { mode: "json" }),
    properties: text("properties", { mode: "json" }),
    loadCases: text("load_cases", { mode: "json" }),
    page: numeric("page", { mode: "number" }),
    specSet: integer("spec_set_id").references(() => reusable_blocks.id, {
      onDelete: "set null",
    }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("products_sku_idx").on(columns.sku),
    index("products_family_idx").on(columns.family),
    index("products_image_idx").on(columns.image),
    index("products_spec_set_idx").on(columns.specSet),
    index("products_updated_at_idx").on(columns.updatedAt),
    index("products_created_at_idx").on(columns.createdAt),
  ],
);

export const variants = sqliteTable(
  "variants",
  {
    id: integer("id").primaryKey(),
    sku: text("sku").notNull(),
    code: text("code"),
    product: integer("product_id")
      .notNull()
      .references(() => products.id, {
        onDelete: "set null",
      }),
    family: integer("family_id").references(() => families.id, {
      onDelete: "set null",
    }),
    size: text("size"),
    packSize: text("pack_size"),
    unit: text("unit").default("pcs"),
    weight: numeric("weight", { mode: "number" }),
    loadRating: text("load_rating"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    notes: text("notes"),
    attributes: text("attributes", { mode: "json" }),
    order: numeric("order", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("variants_sku_idx").on(columns.sku),
    index("variants_code_idx").on(columns.code),
    index("variants_product_idx").on(columns.product),
    index("variants_family_idx").on(columns.family),
    index("variants_image_idx").on(columns.image),
    index("variants_updated_at_idx").on(columns.updatedAt),
    index("variants_created_at_idx").on(columns.createdAt),
  ],
);

export const specifications = sqliteTable(
  "specifications",
  {
    id: integer("id").primaryKey(),
    family: integer("family_id")
      .notNull()
      .references(() => families.id, {
        onDelete: "set null",
      }),
    variant: integer("variant_id").references(() => variants.id, {
      onDelete: "set null",
    }),
    key: text("key").notNull(),
    value: text("value"),
    unit: text("unit"),
    order: numeric("order", { mode: "number" }),
    fullCopy: text("full_copy"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("specifications_family_idx").on(columns.family),
    index("specifications_variant_idx").on(columns.variant),
    index("specifications_updated_at_idx").on(columns.updatedAt),
    index("specifications_created_at_idx").on(columns.createdAt),
  ],
);

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    alt: text("alt"),
    kind: text("kind"),
    croppedTo: text("cropped_to"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: text("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: text("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: text("sizes_thumbnail_filename"),
    sizes_card_url: text("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: text("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: text("sizes_card_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
  ],
);

export const reusable_blocks_blocks_spec_table_rows = sqliteTable(
  "reusable_blocks_blocks_spec_table_rows",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    key: text("key"),
    value: text("value"),
    unit: text("unit"),
  },
  (columns) => [
    index("reusable_blocks_blocks_spec_table_rows_order_idx").on(
      columns._order,
    ),
    index("reusable_blocks_blocks_spec_table_rows_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [reusable_blocks_blocks_spec_table.id],
      name: "reusable_blocks_blocks_spec_table_rows_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const reusable_blocks_blocks_spec_table = sqliteTable(
  "reusable_blocks_blocks_spec_table",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    title: text("title"),
    blockName: text("block_name"),
  },
  (columns) => [
    index("reusable_blocks_blocks_spec_table_order_idx").on(columns._order),
    index("reusable_blocks_blocks_spec_table_parent_id_idx").on(
      columns._parentID,
    ),
    index("reusable_blocks_blocks_spec_table_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [reusable_blocks.id],
      name: "reusable_blocks_blocks_spec_table_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const reusable_blocks_blocks_load_table = sqliteTable(
  "reusable_blocks_blocks_load_table",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    caseName: text("case_name"),
    span: text("span"),
    load: text("load"),
    blockName: text("block_name"),
  },
  (columns) => [
    index("reusable_blocks_blocks_load_table_order_idx").on(columns._order),
    index("reusable_blocks_blocks_load_table_parent_id_idx").on(
      columns._parentID,
    ),
    index("reusable_blocks_blocks_load_table_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [reusable_blocks.id],
      name: "reusable_blocks_blocks_load_table_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const reusable_blocks = sqliteTable(
  "reusable_blocks",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    type: text("type", {
      enum: ["table", "spec-group", "definition", "demo"],
    }).default("table"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("reusable_blocks_updated_at_idx").on(columns.updatedAt),
    index("reusable_blocks_created_at_idx").on(columns.createdAt),
  ],
);

export const blogs_tags = sqliteTable(
  "blogs_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    tag: text("tag"),
  },
  (columns) => [
    index("blogs_tags_order_idx").on(columns._order),
    index("blogs_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [blogs.id],
      name: "blogs_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const blogs_blocks_rich_text = sqliteTable(
  "blogs_blocks_rich_text",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    body: text("body", { mode: "json" }),
    blockName: text("block_name"),
  },
  (columns) => [
    index("blogs_blocks_rich_text_order_idx").on(columns._order),
    index("blogs_blocks_rich_text_parent_id_idx").on(columns._parentID),
    index("blogs_blocks_rich_text_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [blogs.id],
      name: "blogs_blocks_rich_text_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const blogs_blocks_spec_table = sqliteTable(
  "blogs_blocks_spec_table",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: text("id").primaryKey(),
    block: integer("block_id").references(() => reusable_blocks.id, {
      onDelete: "set null",
    }),
    blockName: text("block_name"),
  },
  (columns) => [
    index("blogs_blocks_spec_table_order_idx").on(columns._order),
    index("blogs_blocks_spec_table_parent_id_idx").on(columns._parentID),
    index("blogs_blocks_spec_table_path_idx").on(columns._path),
    index("blogs_blocks_spec_table_block_idx").on(columns.block),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [blogs.id],
      name: "blogs_blocks_spec_table_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const blogs = sqliteTable(
  "blogs",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    author: integer("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    category: text("category"),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    readTime: text("read_time"),
    excerpt: text("excerpt"),
    coverImage: integer("cover_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    featured: integer("featured", { mode: "boolean" }).default(false),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("blogs_slug_idx").on(columns.slug),
    index("blogs_author_idx").on(columns.author),
    index("blogs_cover_image_idx").on(columns.coverImage),
    index("blogs_updated_at_idx").on(columns.updatedAt),
    index("blogs_created_at_idx").on(columns.createdAt),
  ],
);

export const audits = sqliteTable(
  "audits",
  {
    id: integer("id").primaryKey(),
    operation: text("operation").notNull(),
    leaf: text("leaf"),
    decisionId: text("decision_id"),
    contract: text("contract"),
    beforeValue: text("before_value", { mode: "json" }),
    afterValue: text("after_value", { mode: "json" }),
    resolution: integer("resolution_id").references(() => families.id, {
      onDelete: "set null",
    }),
    product: integer("product_id").references(() => products.id, {
      onDelete: "set null",
    }),
    at: text("at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("audits_resolution_idx").on(columns.resolution),
    index("audits_product_idx").on(columns.product),
    index("audits_updated_at_idx").on(columns.updatedAt),
    index("audits_created_at_idx").on(columns.createdAt),
  ],
);

export const roles = sqliteTable(
  "roles",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    isAdmin: integer("is_admin", { mode: "boolean" }).default(false),
    isOwner: integer("is_owner", { mode: "boolean" }).default(false),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("roles_name_idx").on(columns.name),
    index("roles_updated_at_idx").on(columns.updatedAt),
    index("roles_created_at_idx").on(columns.createdAt),
  ],
);

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    isAdmin: integer("is_admin", { mode: "boolean" }).default(false),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    resetPasswordRequestedAt: text("reset_password_requested_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    categoriesID: integer("categories_id"),
    familiesID: integer("families_id"),
    productsID: integer("products_id"),
    variantsID: integer("variants_id"),
    specificationsID: integer("specifications_id"),
    mediaID: integer("media_id"),
    "reusable-blocksID": integer("reusable_blocks_id"),
    blogsID: integer("blogs_id"),
    auditsID: integer("audits_id"),
    rolesID: integer("roles_id"),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_families_id_idx").on(
      columns.familiesID,
    ),
    index("payload_locked_documents_rels_products_id_idx").on(
      columns.productsID,
    ),
    index("payload_locked_documents_rels_variants_id_idx").on(
      columns.variantsID,
    ),
    index("payload_locked_documents_rels_specifications_id_idx").on(
      columns.specificationsID,
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_reusable_blocks_id_idx").on(
      columns["reusable-blocksID"],
    ),
    index("payload_locked_documents_rels_blogs_id_idx").on(columns.blogsID),
    index("payload_locked_documents_rels_audits_id_idx").on(columns.auditsID),
    index("payload_locked_documents_rels_roles_id_idx").on(columns.rolesID),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["familiesID"]],
      foreignColumns: [families.id],
      name: "payload_locked_documents_rels_families_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["productsID"]],
      foreignColumns: [products.id],
      name: "payload_locked_documents_rels_products_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["variantsID"]],
      foreignColumns: [variants.id],
      name: "payload_locked_documents_rels_variants_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["specificationsID"]],
      foreignColumns: [specifications.id],
      name: "payload_locked_documents_rels_specifications_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["reusable-blocksID"]],
      foreignColumns: [reusable_blocks.id],
      name: "payload_locked_documents_rels_reusable_blocks_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blogsID"]],
      foreignColumns: [blogs.id],
      name: "payload_locked_documents_rels_blogs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["auditsID"]],
      foreignColumns: [audits.id],
      name: "payload_locked_documents_rels_audits_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["rolesID"]],
      foreignColumns: [roles.id],
      name: "payload_locked_documents_rels_roles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_categories = relations(categories, ({ one }) => ({
  catalogPdf: one(media, {
    fields: [categories.catalogPdf],
    references: [media.id],
    relationName: "catalogPdf",
  }),
}));
export const relations_families_specifications = relations(
  families_specifications,
  ({ one }) => ({
    _parentID: one(families, {
      fields: [families_specifications._parentID],
      references: [families.id],
      relationName: "specifications",
    }),
  }),
);
export const relations_families_images = relations(
  families_images,
  ({ one }) => ({
    _parentID: one(families, {
      fields: [families_images._parentID],
      references: [families.id],
      relationName: "images",
    }),
  }),
);
export const relations_families_tables_columns = relations(
  families_tables_columns,
  ({ one }) => ({
    _parentID: one(families_tables, {
      fields: [families_tables_columns._parentID],
      references: [families_tables.id],
      relationName: "columns",
    }),
  }),
);
export const relations_families_tables = relations(
  families_tables,
  ({ one, many }) => ({
    _parentID: one(families, {
      fields: [families_tables._parentID],
      references: [families.id],
      relationName: "tables",
    }),
    columns: many(families_tables_columns, {
      relationName: "columns",
    }),
  }),
);
export const relations_families = relations(families, ({ one, many }) => ({
  categoryID: one(categories, {
    fields: [families.categoryID],
    references: [categories.id],
    relationName: "categoryID",
  }),
  catalogPdf: one(media, {
    fields: [families.catalogPdf],
    references: [media.id],
    relationName: "catalogPdf",
  }),
  specifications: many(families_specifications, {
    relationName: "specifications",
  }),
  images: many(families_images, {
    relationName: "images",
  }),
  tables: many(families_tables, {
    relationName: "tables",
  }),
}));
export const relations_products_images = relations(
  products_images,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_images._parentID],
      references: [products.id],
      relationName: "images",
    }),
  }),
);
export const relations_products_specifications = relations(
  products_specifications,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_specifications._parentID],
      references: [products.id],
      relationName: "specifications",
    }),
  }),
);
export const relations_products_variants = relations(
  products_variants,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_variants._parentID],
      references: [products.id],
      relationName: "variants",
    }),
  }),
);
export const relations_products = relations(products, ({ one, many }) => ({
  family: one(families, {
    fields: [products.family],
    references: [families.id],
    relationName: "family",
  }),
  image: one(media, {
    fields: [products.image],
    references: [media.id],
    relationName: "image",
  }),
  images: many(products_images, {
    relationName: "images",
  }),
  specifications: many(products_specifications, {
    relationName: "specifications",
  }),
  variants: many(products_variants, {
    relationName: "variants",
  }),
  specSet: one(reusable_blocks, {
    fields: [products.specSet],
    references: [reusable_blocks.id],
    relationName: "specSet",
  }),
}));
export const relations_variants = relations(variants, ({ one }) => ({
  product: one(products, {
    fields: [variants.product],
    references: [products.id],
    relationName: "product",
  }),
  family: one(families, {
    fields: [variants.family],
    references: [families.id],
    relationName: "family",
  }),
  image: one(media, {
    fields: [variants.image],
    references: [media.id],
    relationName: "image",
  }),
}));
export const relations_specifications = relations(
  specifications,
  ({ one }) => ({
    family: one(families, {
      fields: [specifications.family],
      references: [families.id],
      relationName: "family",
    }),
    variant: one(variants, {
      fields: [specifications.variant],
      references: [variants.id],
      relationName: "variant",
    }),
  }),
);
export const relations_media = relations(media, () => ({}));
export const relations_reusable_blocks_blocks_spec_table_rows = relations(
  reusable_blocks_blocks_spec_table_rows,
  ({ one }) => ({
    _parentID: one(reusable_blocks_blocks_spec_table, {
      fields: [reusable_blocks_blocks_spec_table_rows._parentID],
      references: [reusable_blocks_blocks_spec_table.id],
      relationName: "rows",
    }),
  }),
);
export const relations_reusable_blocks_blocks_spec_table = relations(
  reusable_blocks_blocks_spec_table,
  ({ one, many }) => ({
    _parentID: one(reusable_blocks, {
      fields: [reusable_blocks_blocks_spec_table._parentID],
      references: [reusable_blocks.id],
      relationName: "_blocks_specTable",
    }),
    rows: many(reusable_blocks_blocks_spec_table_rows, {
      relationName: "rows",
    }),
  }),
);
export const relations_reusable_blocks_blocks_load_table = relations(
  reusable_blocks_blocks_load_table,
  ({ one }) => ({
    _parentID: one(reusable_blocks, {
      fields: [reusable_blocks_blocks_load_table._parentID],
      references: [reusable_blocks.id],
      relationName: "_blocks_loadTable",
    }),
  }),
);
export const relations_reusable_blocks = relations(
  reusable_blocks,
  ({ many }) => ({
    _blocks_specTable: many(reusable_blocks_blocks_spec_table, {
      relationName: "_blocks_specTable",
    }),
    _blocks_loadTable: many(reusable_blocks_blocks_load_table, {
      relationName: "_blocks_loadTable",
    }),
  }),
);
export const relations_blogs_tags = relations(blogs_tags, ({ one }) => ({
  _parentID: one(blogs, {
    fields: [blogs_tags._parentID],
    references: [blogs.id],
    relationName: "tags",
  }),
}));
export const relations_blogs_blocks_rich_text = relations(
  blogs_blocks_rich_text,
  ({ one }) => ({
    _parentID: one(blogs, {
      fields: [blogs_blocks_rich_text._parentID],
      references: [blogs.id],
      relationName: "_blocks_richText",
    }),
  }),
);
export const relations_blogs_blocks_spec_table = relations(
  blogs_blocks_spec_table,
  ({ one }) => ({
    _parentID: one(blogs, {
      fields: [blogs_blocks_spec_table._parentID],
      references: [blogs.id],
      relationName: "_blocks_specTable",
    }),
    block: one(reusable_blocks, {
      fields: [blogs_blocks_spec_table.block],
      references: [reusable_blocks.id],
      relationName: "block",
    }),
  }),
);
export const relations_blogs = relations(blogs, ({ one, many }) => ({
  author: one(users, {
    fields: [blogs.author],
    references: [users.id],
    relationName: "author",
  }),
  coverImage: one(media, {
    fields: [blogs.coverImage],
    references: [media.id],
    relationName: "coverImage",
  }),
  tags: many(blogs_tags, {
    relationName: "tags",
  }),
  _blocks_richText: many(blogs_blocks_rich_text, {
    relationName: "_blocks_richText",
  }),
  _blocks_specTable: many(blogs_blocks_spec_table, {
    relationName: "_blocks_specTable",
  }),
}));
export const relations_audits = relations(audits, ({ one }) => ({
  resolution: one(families, {
    fields: [audits.resolution],
    references: [families.id],
    relationName: "resolution",
  }),
  product: one(products, {
    fields: [audits.product],
    references: [products.id],
    relationName: "product",
  }),
}));
export const relations_roles = relations(roles, () => ({}));
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    familiesID: one(families, {
      fields: [payload_locked_documents_rels.familiesID],
      references: [families.id],
      relationName: "families",
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: "products",
    }),
    variantsID: one(variants, {
      fields: [payload_locked_documents_rels.variantsID],
      references: [variants.id],
      relationName: "variants",
    }),
    specificationsID: one(specifications, {
      fields: [payload_locked_documents_rels.specificationsID],
      references: [specifications.id],
      relationName: "specifications",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    "reusable-blocksID": one(reusable_blocks, {
      fields: [payload_locked_documents_rels["reusable-blocksID"]],
      references: [reusable_blocks.id],
      relationName: "reusable-blocks",
    }),
    blogsID: one(blogs, {
      fields: [payload_locked_documents_rels.blogsID],
      references: [blogs.id],
      relationName: "blogs",
    }),
    auditsID: one(audits, {
      fields: [payload_locked_documents_rels.auditsID],
      references: [audits.id],
      relationName: "audits",
    }),
    rolesID: one(roles, {
      fields: [payload_locked_documents_rels.rolesID],
      references: [roles.id],
      relationName: "roles",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  categories: typeof categories;
  families_specifications: typeof families_specifications;
  families_images: typeof families_images;
  families_tables_columns: typeof families_tables_columns;
  families_tables: typeof families_tables;
  families: typeof families;
  products_images: typeof products_images;
  products_specifications: typeof products_specifications;
  products_variants: typeof products_variants;
  products: typeof products;
  variants: typeof variants;
  specifications: typeof specifications;
  media: typeof media;
  reusable_blocks_blocks_spec_table_rows: typeof reusable_blocks_blocks_spec_table_rows;
  reusable_blocks_blocks_spec_table: typeof reusable_blocks_blocks_spec_table;
  reusable_blocks_blocks_load_table: typeof reusable_blocks_blocks_load_table;
  reusable_blocks: typeof reusable_blocks;
  blogs_tags: typeof blogs_tags;
  blogs_blocks_rich_text: typeof blogs_blocks_rich_text;
  blogs_blocks_spec_table: typeof blogs_blocks_spec_table;
  blogs: typeof blogs;
  audits: typeof audits;
  roles: typeof roles;
  users_sessions: typeof users_sessions;
  users: typeof users;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_categories: typeof relations_categories;
  relations_families_specifications: typeof relations_families_specifications;
  relations_families_images: typeof relations_families_images;
  relations_families_tables_columns: typeof relations_families_tables_columns;
  relations_families_tables: typeof relations_families_tables;
  relations_families: typeof relations_families;
  relations_products_images: typeof relations_products_images;
  relations_products_specifications: typeof relations_products_specifications;
  relations_products_variants: typeof relations_products_variants;
  relations_products: typeof relations_products;
  relations_variants: typeof relations_variants;
  relations_specifications: typeof relations_specifications;
  relations_media: typeof relations_media;
  relations_reusable_blocks_blocks_spec_table_rows: typeof relations_reusable_blocks_blocks_spec_table_rows;
  relations_reusable_blocks_blocks_spec_table: typeof relations_reusable_blocks_blocks_spec_table;
  relations_reusable_blocks_blocks_load_table: typeof relations_reusable_blocks_blocks_load_table;
  relations_reusable_blocks: typeof relations_reusable_blocks;
  relations_blogs_tags: typeof relations_blogs_tags;
  relations_blogs_blocks_rich_text: typeof relations_blogs_blocks_rich_text;
  relations_blogs_blocks_spec_table: typeof relations_blogs_blocks_spec_table;
  relations_blogs: typeof relations_blogs;
  relations_audits: typeof relations_audits;
  relations_roles: typeof relations_roles;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
